### PR TITLE
Tolid/changes

### PR DESCRIPTION
**Pull request by tolid**
Hi Kazuho,

I made small changes in Scoreboard.pm:
1. small "refactoring"  in DESTROY sub
2. Now it should be possible to create multilevel base_dir

I hope you will find it useful.

Best,
Anatoliy/tolid

### CODE REVIEW

**Comment by kazuho** [comment]
:+1:

**Comment by kazuho** [comment]
Please let me know if you want a release to CPAN.

**Comment by tolid** [comment]
Hi Kazuko,

Sorry for the very late answer - I was on vacation and didn't check my
mails.
It will be nice if you will make a CPAN release but it is not urgent of
course.

Best regards,
Anatoliy/tolid

**Comment by kazuho** [comment]
@tolid np & thank you for the response.  just released 0.06.

**Pull request merged**
