### PR TITLE
CPAN Pull Request Challenge 2015

### PR DESCRIPTION
**Pull request by fluca1978**
These are a few little changes to the module in order to better check arguments during object creation and to handle in a better way the code reference for the worker_id method. A few other cosmetic commits are within the pull request.

### CODE REVIEW

**Comment by kazuho** [comment]
Thank you for the PR.

* ff8267e - LGTM
* 2f16e8b - personally I prefer using `"` most of the time
* 09d62a2 - base_dir could be something else than a direcory (e.g. a symlink)
* 83e1df8 - needs update after other commits are resolved
* 6d0cf56 - there is no such bug, if $args{worker_id} exists then it would be used, since it is the last argument of the hash created at https://github.com/kazuho/p5-Parallel-Scoreboard/blob/0.07/lib/Parallel/Scoreboard.pm#L31

**Comment by fluca1978** [comment]
I mainly see two problemtic commits here:
- 09d62a2 while it is true that base_dir could be a link, it surely cannot be a file or a socket and therefore the user should get a chance to find out why the base_dir cannot be handled. Should we add a more strict test towards dir/links only?
- 6d0cf56 while working_id was working right (I did not reported it as a bug), it is not checked to be a subroutine, and that could cause a runtime error. My idea was to prevent this in the very beginning.

What do you think?

**Comment by kazuho** [comment]
We definitely not want to change the behavior.

Therefore, the only chance of getting such assertions merged is when we come up with a nifty way of making such assertions without changing the behavior.

Regarding 09d62a2 I am not sure `-s` and `-d` are sufficient checks.  And such checks have false positives (e.g. when a directory that is not writable by the program is specified).

Regarding 6d0cf56,  not all callable objects are guaranteed to return ref($obj) eq 'CODE', and therefore I am backwards against doing such checks.

Generally speaking, I am not sure if it is worth trying to make such assertions considering the fact that Perl is a duck-typing proglang.

**Comment by miyagawa** [comment]
>  that could cause a runtime error. My idea was to prevent this in the very beginning.

An error is actually better than silently ignoring and changing to the implicit default behavior.

**Comment by miyagawa** [comment]
ff8267e9ba35782141e727a553997f43b2659e24 doesn't sound right to me. bareword `use_test_base` is fine as long as you have a right Test::Base related files in bundled `inc`.

**Comment by miyagawa** [comment]
Actually, a better fix is to remove line 16-17 altogether since Test::Base isn't used at all! @fluca1978 try that patch as a separate PR and i'm sure it will be merged :)

**Pull request closed without merging**
